### ISSUE TITLE
Firewall-rules with comma-seperated list of ports / port-ranges cause parsing-error

### ISSUE THREAD

**Issue by NikGro** [Teifun2/cs-unifi-bouncer#26]
I use some firewall-rules with multiple ports seperated by comma. For example a rule to pass chromecast traffic in between vlans. Unifi requires these to be comma-seperated without spaces (for example "8008,8009,8443"). However, at least as far as i can tell from the logs, when grabbing current firewall-rules this causes the container to crash.

`INFO Initializing new UniFi client                
{"level":"info","time":"2025-03-31T02:02:25+02:00","message":"Zone Based Firewall: true"}
{"level":"fatal","error":"unable to decode body: GET /proxy/network/v2/api/site/default/firewall-policies unable to unmarshal alias: unable to unmarshal alias: strconv.Atoi: parsing \"8443,8008,8009\": invalid syntax","time":"2025-03-31T02:02:26+02:00","message":"Failed to get firewall policies"}`

**Comment by NikGro** [comment]
This also applies for port-ranges

`INFO Initializing new UniFi client                
{"level":"info","time":"2025-03-31T02:09:37+02:00","message":"Zone Based Firewall: true"}
{"level":"fatal","error":"unable to decode body: GET /proxy/network/v2/api/site/default/firewall-policies unable to unmarshal alias: unable to unmarshal alias: strconv.Atoi: parsing \"32768-61000\": invalid syntax","time":"2025-03-31T02:09:37+02:00","message":"Failed to get firewall policies"}
`

**Comment by Teifun2** [comment]
Hmmmhmmm interesting. 

This seems to be a issue with the new api library @filipowm

Maybe wee need to open an issue there 😢 
https://github.com/filipowm/go-unifi

Im not doing the parsing of the responses myself.

**Comment by NikGro** [comment]
Gotya, will open an issue over there!

**Comment by NikGro** [comment]
https://github.com/filipowm/go-unifi/issues/66

**Comment by brendann993** [comment]
Yep this is the same issue I mentioned in https://github.com/Teifun2/cs-unifi-bouncer/issues/6 I thought it only impacted users with IPSEC VPNs enabled however it will impact any users with multiple ports defined directly on the firewall zone policy rather than a port group

**Comment by brendann993** [comment]
https://github.com/filipowm/go-unifi/pull/68 should hopefully fix this once merged (or if someone fixes it better :)) I updated it to allow for a individual port number e.g 400, a range of ports e.g. 400-405, or a port list e.g. 400,4500

**Comment by NikGro** [comment]
@brendann993 Strangely, it even comes up when i define ports through a group. I've just tried switching all my manually defined ones to groups. Log-Messages are identical to the ones above. I have a PIA-VPN-Client configured but its not in use if that helps / makes a difference.

**Comment by brendann993** [comment]
Look at the non-editable rules (normally towards the bottom), it's likely there is one down the bottom that still has ports individually defined and those rules you can't update. 
Either way the pull request I've submitted to go-unifi should fix it, been running the last couple of hours without a hitch.

**Comment by NikGro** [comment]
I was thinking this at first too!

However, the logs only show one set of ports that are attempted to be parsed before the crash occurs.

To test this further, I've switched all my rules to objects for ports instead of manually entering them. After that, I've disabled them one by one.

With each one disabled, the logs showed the ports from the next self-Made rule, also including those with objects for ports, attempting to be parsed and then causing the crash.

When I disable all manually created rules, the ones automatically provided by unifi do cause the same parsing error as well tho.

I'm glad that there's a possible fix already in the pipeline! Just wanted to make sure I provide all the details I can on my end!

**Comment by NikGro** [comment]
For reference: Here's one of my android-tv rules using a object for ports:

![Image](https://github.com/user-attachments/assets/0bd45f9f-2910-4be8-88a4-79e051e3c1b1)



Here's the crash-log containing those same ports:

![Image](https://github.com/user-attachments/assets/a2e39fa7-c588-4b1f-8ded-087abd4296d6)

**Comment by Teifun2** [comment]
I am a little blocked by the API here. 

I hope the MR can resolve the issues. I will however try to replicate it and if needed check if i can do something to fix this on my side. 

This will take some time. Sorry :(

**Comment by NikGro** [comment]
@Teifun2  A fix / new version was released for the API 🙏

**Comment by LucasJanin** [comment]
Hi @Teifun2 

I have the same issue.  
Do you have any updates on this topic?  
Thank you!

```
{"level":"info","time":"2025-06-13T18:56:01Z","message":"Starting cs-unifi-bouncer with version: v1.1.1"}
time="2025-06-13T18:56:01Z" level=info msg="Using API key auth"
{"level":"info","time":"2025-06-13T18:56:01Z","message":"Connecting to unifi"}
INFO Initializing new UniFi client                
{"level":"info","time":"2025-06-13T18:56:02Z","message":"Zone Based Firewall: true"}
{"level":"fatal","error":"unable to decode body: GET /v2/api/site/default/firewall-policies unable to unmarshal alias: unable to unmarshal alias: json: cannot unmarshal number into Go struct field .Alias.app_ids of type string","time":"2025-06-13T18:56:02Z","message":"Failed to get firewall policies"}
```

**Comment by brendann993** [comment]
This won't be an issue with this repo, its a upstream issue in the [go-unifi](https://github.com/filipowm/go-unifi/) library. Its likely https://github.com/filipowm/go-unifi/blob/main/codegen/v2/FirewallZonePolicy.json needs to be updated so that destination.app_ids supports a number (Im taking a guess based on your error "cannot unmarshal number into Go struct field") and probably app_category_ids as well

**Comment by Teifun2** [comment]
Correct there is already another issue open discussing this. #41

Please mention the app_ids there. As it currently only mentions app_category_ids.

The library has not yet fixed this.

**Comment by andreasbrett** [comment]
@Teifun2 what's your strategy on going forward with the upstream library? I see that you're using a fork atm so would you be willing to fix this issue by merging the above mentioned PR in your fork?

**Comment by Teifun2** [comment]
@andreasbrett that's actually a good point.

I will continue to fix and use my fixed library as long as the open prs are not merged in the original library.

I forgot a little yesterday, but it's possible that this issue is already resolved in the newest version!

**Comment by Teifun2** [comment]
This PR should have fixed array parsing/validation issues.
https://github.com/Teifun2/go-unifi/pull/1

Is also open to the original library.

**Comment by andreasbrett** [comment]
> Correct there is already another issue open discussing this. [#41](https://github.com/Teifun2/cs-unifi-bouncer/issues/41)
> 
> Please mention the app_ids there. As it currently only mentions app_category_ids.
> 
> The library has not yet fixed this.

This is still an issue. Using v1.2.0 I still get unmarshalling errors for app_ids.

```
{"level":"info","time":"2025-09-02T06:35:46Z","message":"Starting cs-unifi-bouncer with version: v1.2.0"}
time="2025-09-02T06:35:46Z" level=info msg="Using API key auth"
{"level":"info","time":"2025-09-02T06:35:46Z","message":"Connecting to unifi"}
INFO Initializing new UniFi client
{"level":"info","time":"2025-09-02T06:35:47Z","message":"Zone Based Firewall: true"}
{"level":"fatal","error":"unable to decode body: GET /proxy/network/v2/api/site/default/firewall-policies unable to unmarshal alias: unable to unmarshal alias: json: cannot unmarshal number into Go struct field .Alias.app_ids of type string","time":"2025-09-02T06:35:47Z","message":"Failed to get firewall policies"}
```

**Comment by Teifun2** [comment]
Dang ok. Thanks I will check once more!

**Comment by andreasbrett** [comment]
Thank you, very much appreciated!

**Comment by Teifun2** [comment]
Should work with v1.2.1 i tested it localy

**Comment by andreasbrett** [comment]
> Should work with v1.2.1 i tested it localy

Works for me now! Thank you for the quick fix.
